name: Haiku
on:
  schedule:
    - cron: '10 9 * * *'
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Haiku.yml'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Haiku.yml'


concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Haiku:
    strategy:
      matrix:
        release: [""]
    runs-on: ubuntu-latest
    env:
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_ACME_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v7
    - uses: anyvm-org/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8080
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - name: Set CASE
      if: github.event_name == 'push'
      shell: bash
      env:
        HEAD_COMMIT_MSG: ${{ github.event.head_commit.message }}
      run: |
        _case="$(printf '%s' "$HEAD_COMMIT_MSG" | tr ' \t' '\n\n' | grep '^CASE=le_test_' | head -1 | cut -d '=' -f 2- || true)"
        if [ -n "$_case" ]; then
          echo "CASE=$_case" >> "$GITHUB_ENV"
        fi
    - uses: vmactions/haiku-vm@v1
      with:
        envs: 'TestingDomain TEST_PREFERRED_CHAIN TEST_ACME_Server CASE'
        debug-on-error: ${{ vars.DEBUG_ON_ERROR }}
        cache-after-prepare: true
        nat: |
          "8080": "80"
        prepare: |
          mkdir -p /boot/home/.cache
          pkgman install -y cronie
        release: ${{ matrix.release }}
        sync: rsync
        run: ./letest.sh
