name: Linux
on:
  schedule:
    - cron: '10 9 * * *'
  workflow_dispatch:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Linux.yml'
      - 'plat.conf'
  pull_request:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/Linux.yml'
      - 'plat.conf'

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  Docker:
    strategy:
      matrix:
        os: ["ubuntu:latest", "debian:latest", "almalinux:latest", "fedora:latest", "opensuse/leap:latest", "alpine:latest", "oraclelinux:8", "kalilinux/kali", "archlinux:latest",  "gentoo/stage3", "tatsushid/tinycore"]
    runs-on: ubuntu-latest
    env:
      DEBUG: 1
      TEST_PREFERRED_CHAIN: (STAGING) Pretend Pear X1
      TEST_ACME_Server: "LetsEncrypt.org_test"
    steps:
    - uses: actions/checkout@v4
    - uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 80
    - name: Set envs
      run: echo "TestingDomain=${{steps.tunnel.outputs.server}}" >> $GITHUB_ENV
    - name: Run acmetest
      run: |
        ./rundocker.sh  testplat ${{ matrix.os }}
